erDiagram
    POST ||--o{ USER : "created by"
    POST ||--|{ ALBUM : "shares user with"
    PHOTO ||--o{ ALBUM : "belongs to"
    POST {
        number userId
        string body
        date date
        string title
        string views
    }
    USER {
        number id
        string email
        string name
        string phone
        string username
        string website
    }
    ALBUM {
        number id
        number userId
        string title
    }
    PHOTO {
        number albumId
        string thumbnailUrl
        string title
        string url
    }
