erDiagram
    scheduleitem {
        string type
        number id
        string channel
        string show
        string runDateTime
        string runBump
        string runLock
        string crawlLength
        string cgExempt
        number idType
        string runStatus
        boolean deleted
        string filler
        string liveCaptions
        string liveTranslations
        boolean hasFiles
        boolean hasValidFile
        boolean hasInvalidFile
        boolean hasProcessingFile
        string secondaryAudioProgramming
        boolean hasNetworkBroadcastEvents
        boolean hasNetworkBroadcastErrors
    }
    show {
        string type
        string location
        number id
        string title
        string cgExempt
        string eventDate
        string lastModified
        string liveIpExempt
        string podcastExempt
        string project
        string reels
        string vods
        string cgTitle
        string runCount
        string thumbnailImage.url
        string thumbnail
        string thumbnailOptions
        number customFields.id
        string customFields.showField
        string customFields.type
        string customFields.fieldName
        string totalRunTime
        string killDateEnd
        string modified
        string generateCaptions
        boolean hasCaptions
        boolean isOnReflectPlus
        string showThumbnails
        string generateTranslations
        string generateCaptionsSecondary
        string crawlLength
        string firstRuns
        string created
        string captionLanguage
        string captionLanguageSecondary
        string comments
        number localId
        string killDateStart
        string bugText
        string crawlText
        string custom1
        string custom2
        string custom3
        string custom4
        string custom5
        string custom6
        string custom7
        string custom8
    }
    channel {
        string type
        number id
        string name
        string primaryLocation
        string primaryOutput
        string interstitialDwell
        string channelContactInfo
        number automationOverriden
        string brandingConfig
        string squeezeBackEnabled
        string liveStreams
    }
