name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: stable

      - name: Install deps
        run: bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Run tests
        run: bun run test
